name: crawl_all_in_one

on:
  workflow_dispatch:
  push:
    paths:
      - 'crawl_all_in_one.py'
      - '.github/workflows/crawl_all_in_one.yml'
  schedule:
    - cron: '0 22 * * *' # 北京时间早上6点

jobs:
  run-task:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          python crawl_all_in_one.py

      - name: Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add results/
          git diff --quiet && git diff --staged --quiet || (git commit -m "auto update $(date)" && git push)
